//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolidayBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeHoliday
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public Nullable<int> RemainingLeaves { get; set; }
        public Nullable<System.DateTime> HolidayBookedFrom { get; set; }
        public Nullable<System.DateTime> HolidayBookedTill { get; set; }
        public string Reason { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
